services:
  db:
    image: postgres:18.1-alpine3.22
    container_name: postgres_getajob
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer_getajob
    restart: always
    ports:
      - "${ADMINER_EXTERNAL_PORT}:8080"
    depends_on:
      - db

  api:
    container_name: go_api_getajob
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./apps/api:/app
      - ./.env:/app/.env
    ports:
      - "${API_EXTERNAL_PORT}:8080"
    depends_on:
      - db
    command: ["air"]
    restart: unless-stopped

  web:
    container_name: nextjs_getajob
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env
    ports:
      - "${WEB_EXTERNAL_PORT}:3000"
    depends_on:
      - api
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://api:8080

volumes:
  postgres_data:
