CREATE TABLE jobs (
	id SERIAL PRIMARY KEY,
	user_id INT REFERENCES users(id) ON DELETE CASCADE,
	title VARCHAR(255) UNIQUE NOT NULL,
	company VARCHAR(255) NOT NULL,
	location VARCHAR(255) NOT NULL,
	salary DECIMAL(15, 2) NOT NULL,
	description VARCHAR(2048) NULL,
	requirements VARCHAR(2048) NOT NULL,
	current_status CHAR(50) NOT NULL,
	notes VARCHAR(2048) NULL,
	source_url VARCHAR(2048) NOT NULL,
	application_date TIMESTAMP NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(), 
	updated_at TIMESTAMP NULL
);
