// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (title, source_url, salary, description, requirements, current_status, notes, application_date, created_at, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), $9)
RETURNING id, title, company, salary, description, requirements, current_status, notes, source_url, application_date, created_at, updated_at, user_id
`

type CreateJobParams struct {
	Title           string
	SourceUrl       string
	Salary          pgtype.Numeric
	Description     pgtype.Text
	Requirements    string
	CurrentStatus   string
	Notes           pgtype.Text
	ApplicationDate pgtype.Timestamp
	UserID          pgtype.Int4
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.SourceUrl,
		arg.Salary,
		arg.Description,
		arg.Requirements,
		arg.CurrentStatus,
		arg.Notes,
		arg.ApplicationDate,
		arg.UserID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Salary,
		&i.Description,
		&i.Requirements,
		&i.CurrentStatus,
		&i.Notes,
		&i.SourceUrl,
		&i.ApplicationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :execresult
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteJob, id)
}

const getAllJobs = `-- name: GetAllJobs :many
SELECT id, title, company, salary, description, requirements, current_status, notes, source_url, application_date, created_at, updated_at, user_id FROM jobs WHERE user_id = $1 ORDER BY id
`

func (q *Queries) GetAllJobs(ctx context.Context, userID pgtype.Int4) ([]Job, error) {
	rows, err := q.db.Query(ctx, getAllJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Salary,
			&i.Description,
			&i.Requirements,
			&i.CurrentStatus,
			&i.Notes,
			&i.SourceUrl,
			&i.ApplicationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobById = `-- name: GetJobById :one
SELECT id, title, company, salary, description, requirements, current_status, notes, source_url, application_date, created_at, updated_at, user_id FROM jobs WHERE id = $1
`

func (q *Queries) GetJobById(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRow(ctx, getJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Salary,
		&i.Description,
		&i.Requirements,
		&i.CurrentStatus,
		&i.Notes,
		&i.SourceUrl,
		&i.ApplicationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET 
	title = $1,
	source_url = $2,
	salary = $3,
	description = $4,
	requirements = $5,
	current_status = $6,
	notes = $7,
	application_date = $8,
	updated_at = NOW()
WHERE id = $9
RETURNING id, title, company, salary, description, requirements, current_status, notes, source_url, application_date, created_at, updated_at, user_id
`

type UpdateJobParams struct {
	Title           string
	SourceUrl       string
	Salary          pgtype.Numeric
	Description     pgtype.Text
	Requirements    string
	CurrentStatus   string
	Notes           pgtype.Text
	ApplicationDate pgtype.Timestamp
	ID              int32
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.Title,
		arg.SourceUrl,
		arg.Salary,
		arg.Description,
		arg.Requirements,
		arg.CurrentStatus,
		arg.Notes,
		arg.ApplicationDate,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Salary,
		&i.Description,
		&i.Requirements,
		&i.CurrentStatus,
		&i.Notes,
		&i.SourceUrl,
		&i.ApplicationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
