// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    user_id,
    title, 
    company, 
    location, 
    salary, 
    description, 
    requirements, 
    application_status,
    notes, 
    source_url, 
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
RETURNING id, user_id, title, company, location, salary, description, requirements, application_status, status_changed_at, notes, source_url, contact_info, created_at, updated_at
`

type CreateJobParams struct {
	UserID            pgtype.Int4
	Title             string
	Company           string
	Location          string
	Salary            pgtype.Numeric
	Description       pgtype.Text
	Requirements      string
	ApplicationStatus string
	Notes             pgtype.Text
	SourceUrl         string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.UserID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Salary,
		arg.Description,
		arg.Requirements,
		arg.ApplicationStatus,
		arg.Notes,
		arg.SourceUrl,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Salary,
		&i.Description,
		&i.Requirements,
		&i.ApplicationStatus,
		&i.StatusChangedAt,
		&i.Notes,
		&i.SourceUrl,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :execresult
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteJob, id)
}

const getAllJobs = `-- name: GetAllJobs :many
SELECT id, user_id, title, company, location, salary, description, requirements, application_status, status_changed_at, notes, source_url, contact_info, created_at, updated_at FROM jobs WHERE user_id = $1 ORDER BY id
`

func (q *Queries) GetAllJobs(ctx context.Context, userID pgtype.Int4) ([]Job, error) {
	rows, err := q.db.Query(ctx, getAllJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Salary,
			&i.Description,
			&i.Requirements,
			&i.ApplicationStatus,
			&i.StatusChangedAt,
			&i.Notes,
			&i.SourceUrl,
			&i.ContactInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobById = `-- name: GetJobById :one
SELECT id, user_id, title, company, location, salary, description, requirements, application_status, status_changed_at, notes, source_url, contact_info, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobById(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRow(ctx, getJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Salary,
		&i.Description,
		&i.Requirements,
		&i.ApplicationStatus,
		&i.StatusChangedAt,
		&i.Notes,
		&i.SourceUrl,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET 
    title = $1,
    company = $2,
    location = $3,
    salary = $4,
    description = $5,
    requirements = $6,
    application_status = $7,
	status_changed_at = CASE 
		WHEN application_status != $7 THEN NOW() 
		ELSE status_changed_at 
	END,
    notes = $8,
    source_url = $9,
    updated_at = NOW()
WHERE id = $10
RETURNING id, user_id, title, company, location, salary, description, requirements, application_status, status_changed_at, notes, source_url, contact_info, created_at, updated_at
`

type UpdateJobParams struct {
	Title             string
	Company           string
	Location          string
	Salary            pgtype.Numeric
	Description       pgtype.Text
	Requirements      string
	ApplicationStatus string
	Notes             pgtype.Text
	SourceUrl         string
	ID                int32
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Salary,
		arg.Description,
		arg.Requirements,
		arg.ApplicationStatus,
		arg.Notes,
		arg.SourceUrl,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Salary,
		&i.Description,
		&i.Requirements,
		&i.ApplicationStatus,
		&i.StatusChangedAt,
		&i.Notes,
		&i.SourceUrl,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
