// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID              int32
	Title           string
	Company         string
	Salary          pgtype.Numeric
	Description     pgtype.Text
	Requirements    string
	CurrentStatus   string
	Notes           pgtype.Text
	SourceUrl       string
	ApplicationDate pgtype.Timestamp
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	UserID          pgtype.Int4
}

type Resume struct {
	ID        int32
	Label     string
	FileUrl   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	UserID    pgtype.Int4
}

type User struct {
	ID        int32
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Deleted   bool
}
