// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resumes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResume = `-- name: CreateResume :one
INSERT INTO ats_resumes (label, content, created_at, user_id)
VALUES ($1, $2, NOW(), $3)
RETURNING id, user_id, label, content, created_at, updated_at
`

type CreateResumeParams struct {
	Label   string
	Content string
	UserID  pgtype.Int4
}

func (q *Queries) CreateResume(ctx context.Context, arg CreateResumeParams) (Resume, error) {
	row := q.db.QueryRow(ctx, createResume, arg.Label, arg.Content, arg.UserID)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResume = `-- name: DeleteResume :execresult
DELETE FROM ats_resumes WHERE id = $1
`

func (q *Queries) DeleteResume(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteResume, id)
}

const getAllResumes = `-- name: GetAllResumes :many
SELECT id, user_id, label, content, created_at, updated_at FROM ats_resumes WHERE user_id = $1 ORDER BY id
`

func (q *Queries) GetAllResumes(ctx context.Context, userID pgtype.Int4) ([]Resume, error) {
	rows, err := q.db.Query(ctx, getAllResumes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resume
	for rows.Next() {
		var i Resume
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResumeById = `-- name: GetResumeById :one
SELECT id, user_id, label, content, created_at, updated_at FROM ats_resumes WHERE id = $1
`

func (q *Queries) GetResumeById(ctx context.Context, id int32) (Resume, error) {
	row := q.db.QueryRow(ctx, getResumeById, id)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResume = `-- name: UpdateResume :one
UPDATE ats_resumes
SET 
	label = $1,
	content = $2,
	updated_at = NOW()
WHERE id = $3
RETURNING id, user_id, label, content, created_at, updated_at
`

type UpdateResumeParams struct {
	Label   string
	Content string
	ID      int32
}

func (q *Queries) UpdateResume(ctx context.Context, arg UpdateResumeParams) (Resume, error) {
	row := q.db.QueryRow(ctx, updateResume, arg.Label, arg.Content, arg.ID)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
