// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, created_at)
VALUES ($1, $2, NOW())
RETURNING id, username, email, password, role, created_at, updated_at, deleted
`

type CreateUserParams struct {
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password, role, created_at, updated_at, deleted FROM users WHERE id = $1 AND deleted = FALSE LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :execresult
UPDATE users
SET deleted = TRUE
WHERE id = $1 AND deleted = FALSE
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, softDeleteUser, id)
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
	username = $2,
	email = $3,
	updated_at = NOW()
WHERE id = $1 AND deleted = FALSE
RETURNING id, username, email, password, role, created_at, updated_at, deleted
`

type UpdateUserParams struct {
	ID       int32
	Username string
	Email    string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}
