root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/api"
  bin = "main"
  full_bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500

[log]
  time = true
